"""
This constants file is a file that holds all relevant constant variables for the program
"""

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 800

LINE_ONE_HEIGHT = 560
LINE_TWO_HEIGHT = 460
LINE_THREE_HEIGHT = 360
LINE_FOUR_HEIGHT = 260
LINE_FIVE_HEIGHT = 160
LINE_SIX_HEIGHT = 60

COLUMN_ONE_WIDTH = 92
COLUMN_TWO_WIDTH = 192
COLUMN_THREE_WIDTH = 292
COLUMN_FOUR_WIDTH = 392
COLUMN_FIVE_WIDTH = 492
COLUMN_SIX_WIDTH = 592